Improve TCK error messages
* So it shows the TypeDescriptor's of the parameters.
* Example 1:
    java.lang.AssertionError: Running snippet '<' retrieved from 'python' provider (java class com.oracle.graal.python.tck.PythonProvider) with parameters:
    '[1, 2]' from 'ruby' provider, value: [1, 2] (Meta Object: Array)
    '[true, false]' from 'ruby' provider, value: [true, false] (Meta Object: Array)
    failed:
    Expected PolyglotException, but executed successfully.
    Result: null
    Exception: null
    Snippet: lambda x, y: x < y
    Parameter 0 Snippet: -> { [1, 2] }
    Parameter 0 Declared Return Type: [object & Array<number> & Iterable<number>]
    Parameter 0 Returned Value Type: [object & Iterable<number> & Array<number>]
    Parameter 1 Snippet: -> { [true, false] }
    Parameter 1 Declared Return Type: [object & Array<<any>> & Iterable<<any>>]
    Parameter 1 Returned Value Type: [object & Array<boolean> & Iterable<boolean>]
  vs before:
    java.lang.AssertionError: Running snippet '<' retrieved from 'python' provider (java class com.oracle.graal.python.tck.PythonProvider) with parameters:
    '[1, 2]' from 'ruby' provider, value: [1, 2] (Meta Object: Array)
    '[true, false]' from 'ruby' provider, value: [true, false] (Meta Object: Array)
    failed:
    Expected PolyglotException, but executed successfully.
    Result: null
    Exception: null
    Snippet: lambda x, y: x < y
    Parameter 0 Snippet: -> { [1, 2] }
    Parameter 1 Snippet: -> { [true, false] }
* Example 2:
    java.lang.AssertionError: Running snippet '<' retrieved from 'python' provider (java class com.oracle.graal.python.tck.PythonProvider) with parameters:
    '[1, 2]' from 'ruby' provider, value: [1, 2] (Meta Object: Array)
    '[]' from 'ruby' provider, value: [] (Meta Object: Array)
    failed:
    Expected PolyglotException, but executed successfully.
    Result: null
    Exception: null
    Snippet: lambda x, y: x < y
    Parameter 0 Snippet: -> { [1, 2] }
    Parameter 0 Declared Return Type: [object & Array<number> & Iterable<number>]
    Parameter 0 Returned Value Type: [object & Array<number> & Iterable<number>]
    Parameter 1 Snippet: -> { [] }
    Parameter 1 Declared Return Type: [object & Array<<any>> & Iterable<<any>>]
    Parameter 1 Returned Value Type: [object & Iterable<<all>> & Array<<all>>]
  vs before:
    java.lang.AssertionError: Running snippet '<' retrieved from 'python' provider (java class com.oracle.graal.python.tck.PythonProvider) with parameters:
    '[1, 2]' from 'ruby' provider, value: [1, 2] (Meta Object: Array)
    '[]' from 'ruby' provider, value: [] (Meta Object: Array)
    failed:
    Expected PolyglotException, but executed successfully.
    Result: null
    Exception: null
    Snippet: lambda x, y: x < y
    Parameter 0 Snippet: -> { [1, 2] }
    Parameter 1 Snippet: -> { [] }