Remove loadClass hack to grab class bytes. Make sure to mark any removed anonymous inner classes as removed so that trying to call methods from obsolete code or from a cached value will throw NoSuchMethodErrors.