[GR-53428] Libgraal compilation error: java.lang.NullPointerException: Foreign object reference created in scope is no longer valid
(cherry picked from commit 9a727d85f710f4c8c6ea4ab30a720623ad943b4a)