Throw IvocationTargetException when j.l.r.Method is removed
Keep using NoSuchMethodError or IncompatibleClassChangeError as cause.
The method handle path from 19/20 makes it hard to have the unwrapped
exception so standardize on what that path throws.