Use a valid empty jar for the none NFI backend
* Otherwise this happens when languages/nfi is on module path:
  Error occurred during initialization of boot layer
  java.lang.module.FindException: Error reading /b/b/e/.tmp/tmpxc8nusdg/graalvm/languages/nfi/truffle-nfi-none.jar
  Caused by: java.util.zip.ZipException: zip file is empty