[GR-43444] Add varargs helper for CFunction
On some platforms the varargs calling convention doesn't match regular calls (e.g. darwin-aarch64 or linux-riscv).
Instead of implementing varargs support for @CFunction we add C helpers so that the C compiler resolves the ABI specifics for us.

Example on darwin-aarch64, before:

> Fatal error: j (code 1803168592)

After:

> Fatal error: Failed to create the main Isolate. (code 26)