Fix CheckGraalIntrinsics test failure on aarch64
Error message:

test(org.graalvm.compiler.hotspot.test.CheckGraalIntrinsics)
java.lang.AssertionError: missing Graal intrinsics for:
    java/lang/Thread.onSpinWait()V